# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ac17abc9a3244f4c4cb83882b759f574bb608445eb07e717dda4e7299a9982ed472a7f633bc0e807358016a408f06fd4f9d8a455ce18617baaab340892a1b315

test:
  secret_key_base: cca934d6a4a88d948e3447fb1bc68d021de0a5686a16fb955aa9cdfd18508fa9d871a7d04da8504740fadfcd1f51a6b208574279fbde640adc3dba4a8f828980

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
